### ISSUE TITLE
Run fails due to {{ ansible_eth0.ipv4.address }} being undefined

### ISSUE THREAD

**Issue by beerdedfellow** [gregswift/ansible-ipaserver#6]
Interfaces not always named following the eth* convention. Recommend using {{ ansible_default_ipv4.address }} as used earlier in the role as it avoids relying on an interface name. 

https://github.com/gregswift/ansible-ipaserver/blob/master/tasks/main.yml#L33

Thanks for your work on this!

**Comment by flatfender** [comment]
I solved this by substituting {{ ansible_default_ipv4.address }} since I only had one ipv4 address

**Comment by wejdross** [comment]
`gather_facts = no` can cause the problem :) sometimes we forget about it, but we have to tell ansible to gather facts

**Comment by Anupam02** [comment]
> I solved this by substituting {{ ansible_default_ipv4.address }} since I only had one ipv4 address

It worked perfectly fine for me, thanks
